Method,Name,Error,Occurrences
POST,/doctor/search/,"HTTPConnectionPool(host='ec2-52-77-186-131.ap-southeast-1.compute.amazonaws.com', port=5000): Max retries exceeded with url: /doctor/search/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0798EB50>: Failed to establish a new connection: [Errno 10060] [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'))",26331
POST,/doctor/search/,"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))",1580
POST,/doctor/search/,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",71
POST,/doctor/post/login,"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))",19
POST,/doctor/post/login,"HTTPConnectionPool(host='ec2-52-77-186-131.ap-southeast-1.compute.amazonaws.com', port=5000): Max retries exceeded with url: /doctor/post/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0819D448>: Failed to establish a new connection: [Errno 10060] [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'))",3293
POST,/doctor/post/login,"HTTPConnectionPool(host='ec2-52-77-186-131.ap-southeast-1.compute.amazonaws.com', port=5000): Max retries exceeded with url: /doctor/post/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x188E1CE8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",86
POST,/doctor/search/,"HTTPConnectionPool(host='ec2-52-77-186-131.ap-southeast-1.compute.amazonaws.com', port=5000): Max retries exceeded with url: /doctor/search/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x18C90B68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",4354
